name: API trigger test

on: 
  repository_dispatch:
    types: [evt-1, evt-2]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'From external process ${{github.event.client_payload.somedata}}'

